# Simple Starter Notebook for;
## Cryptocurrency Closing Price Prediction Challenge


Can you predict the closing price for a cryptocurrency? 

The objective of this challenge is to create a machine learning model that will predict closing price for a crypto currency coing. 

In [64]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.impute import KNNImputer

#from google.colab import files

In [65]:
# Load files
train = pd.read_csv('Train.csv')
test = pd.read_csv('Test.csv')
ss = pd.read_csv('SampleSubmission.csv')

In [66]:
# check data shapes
train.shape, test.shape, ss.shape

((12632, 49), (6222, 48), (6222, 2))

In [67]:
# Preview train
train.head()

id  asset_id          open          high           low  \
0  ID_322qz6         1   9422.849081   9428.490628   9422.849081   
1  ID_3239o9         1   7985.359278   7992.059917   7967.567267   
2  ID_323J9k         1  49202.033778  49394.593518  49068.057046   
3  ID_323y5P         1           NaN           NaN           NaN   
4  ID_324kJH         1  10535.737119  10535.737119  10384.798216   

         volume    market_cap  url_shares  unique_url_shares  reddit_posts  \
0  7.131986e+08  1.737635e+11      1689.0              817.0          55.0   
1  4.004755e+08  1.426942e+11       920.0              544.0          20.0   
2  3.017729e+09  9.166977e+11      1446.0              975.0          72.0   
3           NaN           NaN         NaN                NaN          17.0   
4  1.150053e+09  1.921183e+11      1012.0              638.0          24.0   

   ...  percent_change_24h_rank  volume_24h_rank  social_volume_24h_rank  \
0  ...                    606.0              2.0                     1.0   
1  ...                      NaN              NaN                     NaN   
2  ...                    692.0              3.0                     1.0   
3  ...                      NaN              NaN                     NaN   
4  ...                    749.0              2.0                     1.0   

   social_score_24h_rank  medium  youtube  social_volume  percent_change_24h  \
0                    1.0     2.0      5.0           4422            1.434516   
1                    NaN     NaN      NaN           2159           -2.459507   
2                    1.0     NaN      NaN          10602            4.942448   
3                    NaN     NaN      NaN            285                 NaN   
4                    1.0     NaN      2.0           3996            2.609576   

   market_cap_global         close  
0       2.818066e+11   9428.279323  
1       2.126897e+11   7967.567267  
2       1.530712e+12  49120.738484  
3                NaN           NaN  
4       3.386925e+11  10384.798216  

[5 rows x 49 columns]

In [68]:
test.asset_id.unique()

array([1])

In [69]:
test.head()

id  asset_id          open          high           low  \
0  ID_323Sn2         1           NaN           NaN           NaN   
1  ID_325SNW         1  11335.062188  11351.690956  11335.062188   
2  ID_325uzE         1   6322.560756   6328.362354   6294.714484   
3  ID_328qCx         1           NaN           NaN           NaN   
4  ID_3293uJ         1           NaN           NaN           NaN   

         volume    market_cap  url_shares  unique_url_shares  reddit_posts  \
0           NaN           NaN         NaN                NaN           7.0   
1  1.064152e+09  2.101463e+11      1664.0             1045.0          64.0   
2  1.516268e+09  1.153862e+11       397.0              255.0          11.0   
3           NaN           NaN         NaN                NaN           8.0   
4           NaN           NaN         NaN                NaN          26.0   

   ...  market_cap_rank  percent_change_24h_rank  volume_24h_rank  \
0  ...              NaN                      NaN              NaN   
1  ...              1.0                    711.0              2.0   
2  ...              1.0                    715.0              2.0   
3  ...              NaN                      NaN              NaN   
4  ...              NaN                      NaN              NaN   

   social_volume_24h_rank  social_score_24h_rank  medium  youtube  \
0                     NaN                    NaN     NaN      NaN   
1                     1.0                    1.0     1.0      1.0   
2                     1.0                    1.0     NaN      NaN   
3                     NaN                    NaN     NaN      NaN   
4                     NaN                    NaN     NaN      NaN   

   social_volume  percent_change_24h  market_cap_global  
0              9                 NaN                NaN  
1           7245           -0.555698       3.631052e+11  
2           2702            1.689370       1.771075e+11  
3            225                 NaN                NaN  
4             59                 NaN                NaN  

[5 rows x 48 columns]

In [70]:
test.asset_id.unique()

array([1])

In [71]:
ss.head()

id  close
0  ID_323Sn2      0
1  ID_325SNW      0
2  ID_325uzE      0
3  ID_328qCx      0
4  ID_3293uJ      0

# Let's look for missing values

In [72]:
# Check if there any missing values in train set
ax = train.isna().sum().sort_values().plot(kind = 'barh', figsize = (9, 10))
plt.title('Percentage of Missing Values Per Column in Train Set', fontdict={'size':15})
for p in ax.patches:
    percentage ='{:,.0f}%'.format((p.get_width()/train.shape[0])*100)
    width, height =p.get_width(),p.get_height()
    x=p.get_x()+width+0.02
    y=p.get_y()+height/2
    ax.annotate(percentage,(x,y))

In [73]:
# Check if there missing values in test set
ax = test.isna().sum().sort_values().plot(kind = 'barh', figsize = (9, 10))
plt.title('Percentage of Missing Values Per Column in Test Set', fontdict={'size':15})

for p in ax.patches:
    percentage ='{:,.1f}%'.format((p.get_width()/test.shape[0])*100)
    width, height =p.get_width(),p.get_height()
    x=p.get_x()+width+0.02
    y=p.get_y()+height/2
    ax.annotate(percentage,(x,y))

In [92]:
#getting the data types of the data 
#converting categorical features to numbers 
#train.dtypes

In [75]:
#y = train.close

In [76]:
#len(train.id.unique())

12632

In [77]:
#train.asset_id.unique()

array([1])

In [128]:
main_cols = train.columns.difference(['id', 'close'])
impute_columns = train.columns.difference(['id'])

In [129]:
train1 = train[impute_columns]

In [130]:
imputer = KNNImputer(n_neighbors=5) 

In [131]:
df_filled = imputer.fit_transform(train1)

In [108]:
#df_filled

In [132]:
df_new = pd.DataFrame(df_filled, columns = train1.columns, index=train1.index)

In [133]:
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
print(random_grid)


{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt'], 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, None], 'min_samples_split': [2, 5, 10], 'min_samples_leaf': [1, 2, 4], 'bootstrap': [False]}


In [112]:
#train_labels.fillna(0)

In [113]:
#train_labels

In [134]:
from sklearn.ensemble import RandomForestRegressor

# Use the random grid to search for best hyperparameters
# First create the base model to tune
rf = RandomForestRegressor()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 5, verbose=2, random_state=42, n_jobs = -1)
# Fit the random search model



train_descriptors = df_new[main_cols]
train_labels = df_new.close.astype(float)
rf_random.fit(train_descriptors,train_labels )

Fitting 5 folds for each of 5 candidates, totalling 25 fits


/opt/anaconda3/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py:688: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(


RandomizedSearchCV(estimator=RandomForestRegressor(), n_iter=5, n_jobs=-1,
                   param_distributions={'bootstrap': [False],
                                        'max_depth': [10, 20, 30, 40, 50, 60,
                                                      70, 80, 90, 100, 110,
                                                      None],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=42, verbose=2)

In [135]:
test1 = test.drop(['id'], axis=1)
test_df_filled = imputer.fit_transform(test1)
test_df_filled_ = pd.DataFrame(test_df_filled, columns = test1.columns, index=test1.index)
test_descriptors = test_df_filled_

In [136]:
#test_df_filled_.columns

In [137]:
predictions = rf_random.predict(test_descriptors)

In [138]:
predictions

array([55988.22182821, 56189.76797232, 55977.71828025, ...,
       55988.22182821, 55980.37524091, 55977.71828025])

In [139]:
sub_file = ss.copy()
sub_file.close = predictions
sub_file.to_csv('Baseline.csv', index = False)

In [29]:
import numpy as np

from sklearn.datasets import fetch_california_housing
from sklearn.datasets import load_diabetes



rng = np.random.RandomState(42)

X_diabetes, y_diabetes = load_diabetes(return_X_y=True)
X_california, y_california = fetch_california_housing(return_X_y=True)
X_california = X_california[:400]
y_california = y_california[:400]


def add_missing_values(X_full, y_full):
    n_samples, n_features = X_full.shape

    # Add missing values in 75% of the lines
    missing_rate = 0.75
    n_missing_samples = int(n_samples * missing_rate)

    missing_samples = np.zeros(n_samples, dtype=bool)
    missing_samples[: n_missing_samples] = True

    rng.shuffle(missing_samples)
    missing_features = rng.randint(0, n_features, n_missing_samples)
    X_missing = X_full.copy()
    X_missing[missing_samples, missing_features] = np.nan
    y_missing = y_full.copy()

    return X_missing, y_missing


X_miss_california, y_miss_california = add_missing_values(
    X_california, y_california)

X_miss_diabetes, y_miss_diabetes = add_missing_values(
    X_diabetes, y_diabetes)

In [30]:
rng = np.random.RandomState(0)

from sklearn.ensemble import RandomForestRegressor

# To use the experimental IterativeImputer, we need to explicitly ask for it:
from sklearn.experimental import enable_iterative_imputer  # noqa
from sklearn.impute import SimpleImputer, KNNImputer, IterativeImputer
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import make_pipeline


N_SPLITS = 5
regressor = RandomForestRegressor(random_state=0)

In [31]:
def get_scores_for_imputer(imputer, X_missing, y_missing):
    estimator = make_pipeline(imputer, regressor)
    impute_scores = cross_val_score(estimator, X_missing, y_missing,
                                    scoring='neg_mean_squared_error',
                                    cv=N_SPLITS)
    return impute_scores


x_labels = ['Full data',
            'Zero imputation',
            'Mean Imputation',
            'KNN Imputation',
            'Iterative Imputation']

mses_california = np.zeros(5)
stds_california = np.zeros(5)
mses_diabetes = np.zeros(5)
stds_diabetes = np.zeros(5)

In [32]:
def get_impute_knn_score(X_missing, y_missing):
    imputer = KNNImputer(missing_values=np.nan, add_indicator=True)
    knn_impute_scores = get_scores_for_imputer(imputer, X_missing, y_missing)
    return knn_impute_scores.mean(), knn_impute_scores.std()


mses_california[2], stds_california[2] = get_impute_knn_score(
    X_miss_california, y_miss_california)
mses_diabetes[2], stds_diabetes[2] = get_impute_knn_score(X_miss_diabetes,
                                                          y_miss_diabetes)

In [33]:
#mses_california


array([ 0.        ,  0.        , -0.29743643,  0.        ,  0.        ])

In [27]:
# Check if there any missing values in train set
ax = df_filled.isna().sum().sort_values().plot(kind = 'barh', figsize = (9, 10))
plt.title('Percentage of Missing Values Per Column in Train Set', fontdict={'size':15})
for p in ax.patches:
    percentage ='{:,.0f}%'.format((p.get_width()/train.shape[0])*100)
    width, height =p.get_width(),p.get_height()
    x=p.get_x()+width+0.02
    y=p.get_y()+height/2
    ax.annotate(percentage,(x,y))

AttributeError: 'numpy.ndarray' object has no attribute 'isna'

In [ ]:
imputer = KNNImputer(n_neighbors=5) 

imputer.fit_transform(X) #Fit to data, then transform it.


fit(X, y=None) #Fit the imputer on X.

fit_transform(X, y=None, **fit_params) #Fit to data, then transform it.

#Fits transformer to X and y with optional parameters fit_params and returns a transformed version of X. 

get_params(deep=True) #Get parameters for this estimator.

set_params(**params) #Set the parameters of this estimator.

#The method works on simple estimators as well as on nested objects (such as Pipeline). The latter have parameters of the form <component>__<parameter> so that it’s possible to update each component of a nested object.

transform(X) #Impute all missing values in X.


In [ ]:
#find a formula/distribution to fill the values (not with 0) 
https://www.askpython.com/python/examples/impute-missing-data-values
https://scikit-learn.org/stable/modules/impute.html
https://www.kaggle.com/residentmario/simple-techniques-for-missing-data-imputation
https://machinelearningmastery.com/handle-missing-data-python/
https://www.geeksforgeeks.org/python-pandas-dataframe-interpolate/
https://www.geeksforgeeks.org/working-with-missing-data-in-pandas/

In [9]:
# fill missing values 
train = train.fillna(0)
test = test.fillna(0)

In [10]:
# Check for duplicates
train.duplicated().any(), test.duplicated().any()

(False, False)

In [11]:
# Select main columns to be used in training
main_cols = train.columns.difference(['id', 'close'])
X = train[main_cols]
y = train.close.astype(float)

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=42)

In [12]:
# Instantiate model
lm2 = LinearRegression()
# Fit Model
lm2.fit(X_train, y_train)
# Predict
y_pred = lm2.predict(X_test)

In [13]:
# Make predictions in test set and prepare submission file
predictions = lm2.predict(test[main_cols])
sub_file = ss.copy()
sub_file.close = predictions
sub_file.to_csv('Baseline.csv', index = False)

In [14]:
sub_file.head()

id         close
0  ID_323Sn2     -0.316487
1  ID_325SNW  11360.056013
2  ID_325uzE   6306.758106
3  ID_328qCx     -0.239739
4  ID_3293uJ      1.153112

In [15]:
files.download('Baseline.csv') 

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>